name: Publish

on:
  push:
    branches:
      - main
    paths:
      - 'dtk/package.json'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: dtk

    steps:
      - uses: actions/checkout@v4

      - name: Update npm
        run: sudo npm install -g npm@latest

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'
          scope: '@jordanalec'

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish --provenance --access public
